### ISSUE TITLE
Function name and username highlighting issues

### ISSUE THREAD

**Issue by SnaveSutit** [AjaxGb/Sublime-MCFunction#4]
There are a couple errors in highlighting 1.13 function names and player names in some commands:
![temp](https://user-images.githubusercontent.com/28514936/42416495-d217c6e6-823d-11e8-969b-257f28aa382d.png)

**Comment by SnaveSutit** [comment]
I just noticed something similar happens with Json text components:
![image](https://user-images.githubusercontent.com/28514936/42416532-252edf8a-823f-11e8-92fd-788250097ced.png)

**Comment by AjaxGb** [comment]
That's a different syntax highlighter.

![image](https://user-images.githubusercontent.com/7976377/42436190-2c8933be-8327-11e8-88fe-ebd1ef21eca7.png)

**Comment by SnaveSutit** [comment]
Ah, Sorry! I didn't know
